#pragma kernel Preprocess

RWTexture2D<half4> _Tensor;
Texture2D<half4> _Texture;

[numthreads(8, 8, 1)]
void Preprocess(uint3 id : SV_DispatchThreadID)
{
    // Change range from [0, 1] to [-0.5, 0.5]
    _Tensor[id.xy] = half4(_Texture[id.xy].x - 0.5h, _Texture[id.xy].y - 0.5h, _Texture[id.xy].z - 0.5h, 1.0h);
    
    // Just copy from texture to tensor
    //_Tensor[id.xy] = half4(_Texture[id.xy].x, _Texture[id.xy].y, _Texture[id.xy].z, 1.0h);
}
